image: node:hydrogen-slim

stages:
  - test

integration-test-job:
  stage: test
  image: cypress/browsers:latest
  before_script:
    - npm install

  script:
    - npm run test
    - cd reports

  artifacts:
  expire_in: 1 week
    paths:
      - $CI_PROJECT_DIR/reports/
    when: always