image: node:hydrogen-slim

stages:
  - test


integration-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  image: cypress/browsers:latest
  before_script:
    - npm install

  script:
    - npm run test
    - cd reports

  artifacts:
    expire_in: 1 week
    paths:
      - $CI_PROJECT_DIR/reports/
    when: always