version: 2.1

jobs:
  integration-test-job:
    docker:
      - image: cypress/browsers:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test
      - persist_to_workspace:
          root: .
          paths:
            - reports

workflows:
  version: 2
  test:
    jobs:
      - integration-test-job:
          filters:
            branches:
              only:
                - master
